// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterMovieTable_AddColumn_GenreId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterMovieTable_AddColumn_GenreId));
        
        string IMigrationMetadata.Id
        {
            get { return "201711191416040_AlterMovieTable_AddColumn_GenreId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
